# Job to build CI image and push to GitLab registry
# Will only run when triggered directly "build_ci_image=ON"
build_ci_image:
  stage: build
  image: docker:latest
  tags:
    - linux
  services:
    - docker:dind
  rules:
    # git push -o ci.variable="build_ci_image=ON"
    - if: $build_ci_image=="ON"
    - if: $CUSTOM_PIPELINE=="ON"
      when: never

  script: |
    docker login $CI_REGISTRY -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
    docker build --pull --cache-from $CI_DEV_DOCKER_IMAGE:latest -f gitlab/Dockerfile --tag "$CI_DEV_DOCKER_IMAGE:latest" --tag "$CI_DEV_DOCKER_IMAGE:${CI_DEV_DOCKER_VERSION}" .
    docker push "$CI_DEV_DOCKER_IMAGE" --all-tags
